---
version: '3'
services:
  dvwa:
    image: dvwa
    build:
      context: ./.
      dockerfile: dvwa.Dockerfile
    networks:
      my_test:
        aliases:
          - dvwa
          
  selenium:
    image: selenium/standalone-firefox:latest
    logging:
      driver: none
    environment:
      http_proxy: http://Fast123:3128
    networks:
      my_test:
        aliases:
          - selenium

  test:
    image: test
    build:
      context: ./.
      dockerfile: test.Dockerfile
    networks:
      my_test:
        - test_alias
