---
version: '3'
services:
  dvwa:
    image: dvwa
    build:
      context: ./.
      dockerfile: dvwa.Dockerfile
    networks:
      main:
        aliases:
          - dvwa

  fast:
    image: wallarm/fast
    environment:
      WALLARM_API_TOKEN: ${WALLARM_API_TOKEN}
      WALLARM_API_HOST: us1.api.wallarm.com
      CI_MODE: recording
      ALLOWED_HOSTS: dvwa
    networks:
      main:
        aliases:
          - fast

  selenium:
    image: selenium/standalone-firefox:latest
    logging:
      driver: none
    environment:
      http_proxy: http://Fast123:3128
    networks:
      main:
        aliases:
          - selenium

  test:
    image: test
    build:
      context: ./.
      dockerfile: test.Dockerfile
    networks:
      main:

networks:
  main:
